version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-openai
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - .:/app # for development, comment out in production
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
